const languageObject = {
      // welcome: "Forever is a company for manufacturing cosmetics and physiotherapy products.",
      welcome: "Forever",
      dashboard: "Dashboard",
      home: "Home",
      all: "All",
      products: "Products",
      groups: "Groups",
      about: "About",
      logo: "Forever Living Products is a multi-billion dollar company that manufactures and sells hundreds of wellness and beauty products all around the world",
      bestSellers: "Best Sellers",
      latestProducts: "Latest Products",
      highestRated: "Highest Rated",
      aboutForver: "About Forver",
      mainTitle: "Forever Living Products Company",
      subTitle: "A company for manufacturing cosmetics and physiotherapy products",
      aboutParagraph1: "Forever Living Products is a multi-level marketing company that was founded in 1980 in Tempe, Arizona by Rex Maughan.The company has reported a network of 9.3 million distributors and revenue of $4 billion in 2021, and in 2006 they reported having 4,100 employees.",
      aboutParagraph2: "Since 1978, Forever Living Products has been dedicated to seeking nature’s best health and beauty sources and sharing them with the world. We have a passion for helping others look better and feel better, and pride that comes from doing things a little differently. We own our own aloe fields, manufacturing facilities, research and development, quality control laboratories and even our own distribution channels. Everything from plant to product to you.",
      aboutParagraph3: "Millions of people in over 160 countries have discovered the benefits of Forever’s aloe vera products to help them and their families look better and feel better.",
      ingredients: "Ingredients",
      addToCart: "Add to Cart",
      buyViaWhatsApp: "Buy via WhatsApp",
      noProducts: "No Products!",
      noOrders: "No Orders!",
      total: "Total",
      order: "Order",
      orderViaWhatsApp: "Order via WhatsApp",
      title: "Product",
      price: "Price",
      quantity: "Quantity",
      sum: "Sum",
      shipping: "Shipping",
      piece: "piece",
      dateFormat: "en-US",
      inProgress: "In progress",
      cart: "Cart",
      orders: "Orders",
      login: "Login",
      saudi: "Saudi Arabia",
      qatar: "Qatar",
      bahrain: "Bahrain",
      emirates: "Emirates",
      oman: "Sultanate of Oman",
      kuwait: "Kuwait",
      saudiCur: "SAR",
      qatarCur: "QAR",
      bahrainCur: "BHD",
      emiratesCur: "AED",
      omanCur: "OMR",
      kuwaitCur: "KWD",
      searchHint: "Search...",
      noCart: "Cart is empty",
}

export default languageObject;